bug/minor: MySql: fix healthcheck crash
elabftw/elabctl pull request #39
Opened 2024-12-09 08:47 UTC by MoustaphaCamara

update-db-schema fails to parse docker when mysql container has no healthcheck values.

- check if healthcheck is available before continuing. If not detectable, wait 20 seconds and retry.

2024-12-09 09:23 UTC, MoustaphaCamara commented on elabctl.sh
> +                echo
why
```suggestion
                echo
```

2024-12-11 15:01 UTC, NicolasCARPi requested changes
please run through shellcheck and add double quotes where needed

2024-12-12 10:39 UTC, MoustaphaCamara commented
> please run through shellcheck and add double quotes where needed

I fixed for this issue, I'll make another PR to address other shellcheck warnings for this file, so i can test it thoroughly before comitting :)

2024-12-12 14:44 UTC, NicolasCARPi approved these changes
Thanks!

2024-12-12 14:45 UTC, merged

2024-12-23 12:29 UTC, alexander-haller commented
Do you no longer increment versions when committing to master?

2024-12-23 12:41 UTC, NicolasCARPi commented
![image](https://github.com/user-attachments/assets/de9df965-3723-49a6-96f4-1b0852725fb2)